# Setup for devicedb cloud node
version: '3'
services:
  devicedb-cloud:
    build: .
    restart: always
    command:
    - devicedb
    - cluster
    - start
    - -store
    - /var/lib/devicedb/data
    - -snapshot_store
    - /var/lib/devicedb/snapshots
    - -replication_factor
    - "1"
    - -host
    - "0.0.0.0"
    ports:
    - "8080:8080"
    volumes:
    - devicedb-identity:/etc/devicedb
    - devicedb-cloud-data:/var/lib/devicedb
    - ${EDGE_CLIENT_RESOURCES}:/etc/devicedb/shared
volumes:
  devicedb-identity:
  devicedb-cloud-data: